"""Shared Lyrion protocol constants for generic LMS/CometD handling."""

from __future__ import annotations

from music_assistant.constants import CONF_PORT

CONF_LMS_HOST = "lms_host"
CONF_LMS_PORT = CONF_PORT
DEFAULT_LMS_HOST = "127.0.0.1"
DEFAULT_LMS_PORT = 9000
RPC_TIMEOUT = 10
COMETD_RETRY_DELAY = 5
COMETD_CONNECT_TIMEOUT = 35
COMETD_PLAYERSTATUS_TAGS = "tags:cdegilopqrstuyAABEGIKNPSTV"
COMETD_PLAYERSTATUS_SUBSCRIBE_INTERVAL = 60
COMETD_STATUS_STALENESS_FACTOR = 2
COMETD_COMMAND_STATUS_BACKOFF = (0.1, 0.2, 0.4, 0.8, 1.6)
COMETD_COMMAND_STATUS_VERIFY_TIMEOUT = COMETD_COMMAND_STATUS_BACKOFF[0]
COMETD_COMMAND_STATUS_POLL_ATTEMPTS = len(COMETD_COMMAND_STATUS_BACKOFF)
COMETD_STATUS_WATCHDOG_INTERVAL = 30
COMETD_SERVERSTATUS_SUBSCRIBE_INTERVAL = 30
COMETD_SERVERSTATUS_BATCH_SIZE = 500
